FROM node:16

WORKDIR /usr/share/app

ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=admin
ENV KEYCLOAK_REALM = node-integration
ENV KEYCLOAK_AUTH_SERVER_URL=http://localhost:3005/auth/
ENV KEYCLOAK_SSL_REQUIRED=external
ENV KEYCLOAK_RESOURCE=feature-flag
ENV KEYCLOAK_PUBLIC_CLIENT=true
ENV KEYCLOAK_CONFIDENTIAL_PORT=0
ENV KEYCLOAK_VERIFY_TOKEN_AUDIENCE=true,
ENV KEYCLOAK_CREDENTIALS_SECRET=7f48dc36-b1b3-47b3-b92d-6a8e58a47fd9
ENV SESSION_SECRET=f9k2cz05

COPY ./ /usr/share/app/

RUN npm install
RUN npm run build

ENTRYPOINT ["npm" "run serve" ]

EXPOSE 3000

